### ISSUE TITLE
'module' object has no attribute 'Distutils'

### ISSUE THREAD

**Issue by ziziermao** [dahlia/github-distutils#4]
Hey,
 we are getting 'module' object has no attribute 'Distutils' when trying to install  xmlsec==0.3.1 .
The packages we are trying to install are:
tornado==4.2.1
python-saml==2.1.4
isodate==0.5.4
Unidecode==0.4.17
python-ldap==2.4.19
pyyaml==3.11
inject==3.3.1
cython<0.23
xmlsec==0.3.1
logging==0.4.9.6

we tried to set cython==0.22.1 but still getting the same.
Could anyone please help with this?

**Comment by dahlia** [comment]
Sorry.

This project is abandoned, and we recommend not to use this anymore. Because PyPI and pip disallows to download package distributions from other than official PyPI for security reasons.
