### ISSUE TITLE
github-distutils not available on Pypi

### ISSUE THREAD

**Issue by bcopy** [dahlia/github-distutils#5]
Hi,

I can't specify github-distutils as a "setup requires" in my project, because the Pypi repo does not have github-distutils :

https://pypi.python.org/simple/github-distutils/

Can you possibly make it available there again ?

thanks,

Brice

**Comment by dahlia** [comment]
Sorry.

This project is abandoned, and we recommend not to use this anymore. Because PyPI and pip disallows to download package distributions from other than official PyPI for security reasons.
